### ISSUE TITLE
I would like to use 'not_has_key' in themis

### ISSUE THREAD

**Issue by lambdalisue** [thinca/vim-themis#13]
`has_key` の逆バージョンである `not_has_key` 的なものがあると便利です。

`expect` の場合は `not` があるので不要かもしれませんが `assert` の場合は `Assert !has_key(...)` とする必要があり統一感が崩れてしまいます。ご一考いただければ幸いです。

**Comment by thinca** [comment]
機能自体は入れようと思っているんですが、`not_has_key` は英語的にちょっとおかしそうです。何かいい案あったりするでしょうか? 素直にやると `does_not_have_key` になります(長い)。

**Comment by lambdalisue** [comment]
個人的には命名規則がクリアであれば必ずしも英語的である必要は無いと思います（もちろん英語的のほうがベターですが）
別案としては `without_key` とかかなーと思いますが `has_key` との対応性がぱっとわかりにくい…他の方のアイディアも聞きたいですね。

**Comment by lambdalisue** [comment]
あ、 `has_key` に `negative` アトリビュートとかでもいいかも

```vim
assert.has_key(obj, key, { negative: 1 })
```

的な？

**Comment by thinca** [comment]
アトリビュートはそれこそ他との統一性がなくなるのでやりたくないですね。それに第3引数はメッセージにもなっていますし。
にしてもこれ悩むなー。`doesnt_have_key` とかもちょっと考えたけどやっぱり微妙だ…。
ちなみに、`does_not_have_key` にするって言ったら長すぎて嫌とかあります? 今のところこれに傾きつつあります。
なんなら別名(alias)で `not_has_key` と両方提供すると言う手もあります。

**Comment by lambdalisue** [comment]
> アトリビュートはそれこそ他との統一性がなくなるのでやりたくないですね。それに第3引数はメッセージにもなっていますし。

たしかにそうですね、失礼しました。

Alternativeな案ですが have の使用をやめて他の言葉で置き換えるのはどうでしょう？後方互換で `has_key` のほうを alias にするという逆の発想で。

例:

```vim
" Carp::Assert::More 的
assert.exists_key(obj, key)
assert.lacks_key(obj, key)

" Python的（辞書キーのチェックだけじゃなくて配列のチェックもしたほうがいい名前になっちゃいますが）
assert.in(key, obj) "あれ？予約語...
assert.not_in(key, obj)
```

1. exists / lacks  [Perl Carp::Assert::More](http://search.cpan.org/~petdance/Carp-Assert-More-1.12/More.pm#assert_exists%28_%5C%hash,_%5C@keylist_[,$name]_%29)
2. in / not_in [Python unittest](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertIn)

**Comment by thinca** [comment]
in いいですね。実はすでに配列でも使えるので、それ採用しようと思います。ありがとうございます！

**Comment by lambdalisue** [comment]
ぉ、よかった。次期バージョン楽しみにしています！

**Comment by thinca** [comment]
今バリバリ実装していて気付いてしまったんですが、`in` は "要素がある" ことをチェックするもので、"キーがある" ことをチェックするものではない気がしてきました…。

**Comment by thinca** [comment]
となると Perl の奴の方がいいかなぁ。もうちょっと候補探してみます。

**Comment by lambdalisue** [comment]
> in は "要素がある" ことをチェックするもので、"キーがある" ことをチェックするものではない気がしてきました…。

感覚かもしれませんが Python 的には `key in dictionary` ですね。
**「`key` という名前の要素が辞書に存在する」** という受け取り方をすれば別に変ではないかと。

**Comment by thinca** [comment]
確かに、辞書の場合はそうでした。しかしリストの場合は違うんですよね。そもそも辞書と配列で関数分けた方がいいかもですね…。

**Comment by lambdalisue** [comment]
個人的には `key in dictionary` と `value in list` であまり違和感は感じませんが…… Pythonista的なんですかねこの感覚は

**Comment by thinca** [comment]
いや、`list` の場合は `index` が存在するかどうかをチェックしてるのです。動作が違う。

**Comment by lambdalisue** [comment]
> いや、list の場合は index が存在するかどうかをチェックしてるのです。動作が違う。

なるほど、それだとちょっと感覚とズレてしまいますね……

**Comment by thinca** [comment]
そもそもこの2つは同じ関数でやるべきではなかったのかもしれないですねー。つらい。

**Comment by lambdalisue** [comment]
> そもそもこの2つは同じ関数でやるべきではなかったのかもしれないですねー

辞書の場合はキー、配列の場合は要素という感じであればよかったんですがね…

>  index が存在するかどうかをチェック

素朴な疑問なんですが、これって必要なんでしょうか？ Vimscript って虫食いな配列（`a[0], a[5]`）みたいなの作れるんでしたっけ？作れないのであれば `len(a)` の `if` で十分な気が（使用頻度的に）

**Comment by lambdalisue** [comment]
もしくは `assert.indexOf` を新設するとかはいかがでしょう？

**Comment by thinca** [comment]
`indexOf` は配列の要素のインデックスを返すっぽいので違う感じがしますが、この辺りちょっと見直した方が良さそうな感じはありますね。互換性をどうしようかがちょっと悩み。

**Comment by thinca** [comment]
色々悩んだんですが、`key_exists` と `key_not_exists` を新設で追加しようかと思います。これでどうでしょう?

**Comment by lambdalisue** [comment]
:+1:

**Comment by thinca** [comment]
68a324d41a46237ba927d56221ca418c0b77d795

**Comment by thinca** [comment]
Closable?

**Comment by lambdalisue** [comment]
はい。ありがとうございました！
