### ISSUE TITLE
`s:expect(0).to_be_false()` inside while loop throws E488

### ISSUE THREAD

**Issue by cocopon** [thinca/vim-themis#14]
Thank you for your great framework.
I found an unspecified behavior as follows:

```vim
let s:suite = themis#suite('test')
let s:expect = themis#helper('expect')

function! s:suite.works_fine()
	call s:expect(0).to_be_false()
endfunction

function! s:suite.does_not_work()
	let i = 0
	let imax = 10
	while i < imax
		call s:expect(0).to_be_false()
		let i += 1
	endwhile
endfunction
```

Result:

```
% themis themis-test.vim

1..2
ok 1 - test works_fine
not ok 2 - test does_not_work
# function 102()  Line:4  (~/tmp/themis-test.vim)
# Vim(call):E488: Trailing characters

# tests 2
# passes 1
# fails 1
```

Environment:
- OS X 10.10.1
- Vim 7.4 (2013 Aug 10, compiled Dec  4 2014 19:05:45)
- Patch: 1-527

**Comment by thinca** [comment]
Thanks for your report.
It works for me.  (Vim 7.4.527 on Gentoo Linux)
Please more information.  (Or, recheck your environment)

**Comment by cocopon** [comment]
Oops, it seems that vim-themis in my environment used system vim (7.3)...
After setting `$THEMIS_VIM` to new one, it works fine.
I'm sorry to trouble you.

--

どうやらシステム標準のVim(7.3)を参照していたようです…。
`$THEMIS_VIM` で新しいバージョンを指定することで動作しました。
お手数をおかけしました。
