### ISSUE TITLE
cmd.exe で実行した場合にテスト内でインサートモードに入ると表示が崩れる

### ISSUE THREAD

**Issue by machakann** [thinca/vim-themis#19]
cmd.exe 上で実行した場合に、特に編集作業などをしなくてもインサートモードに入ってしまうと表示が崩れてしまうようです。

次のテストスクリプトは正常に終了します
```vim
let s:suite = themis#suite('Test in cmd.exe: case1:')
let s:assert = themis#helper('assert')

function! s:suite.test() abort
  call s:assert.equals(3, 1 + 2)
endfunction
```
![cmddotexe_case1](https://cloud.githubusercontent.com/assets/480049/7811502/e7e402d2-03dd-11e5-859b-29e3dd8c9297.png)

しかし、次のテストでは表示が崩れてしまいます。
```vim
let s:suite = themis#suite('Test in cmd.exe: case2:')
let s:assert = themis#helper('assert')

function! s:suite.test() abort
  normal! i
  call s:assert.equals(3, 1 + 2)
endfunction
```
実行前
![cmddotexe_case2_pre](https://cloud.githubusercontent.com/assets/480049/7811522/0c312552-03de-11e5-9321-0dd0f1bbe973.png)
実行後
![cmddotexe_case2_post](https://cloud.githubusercontent.com/assets/480049/7811527/1614441e-03de-11e5-94e4-3e71a7058682.png)

テスト自体は正しく実行されているようです。また、ほかの端末では観測していません (なので、cmd.exeの問題？)。何か使い方を間違えていたら教えてください。

**Comment by machakann** [comment]
すいません、書き忘れましたが環境は

OS:  Windows 7 64bit
vim 7.4.648 32bit

です。

**Comment by thinca** [comment]
報告ありがとうございます。
この現象なんですが、原因がよくわからず、直せるかどうかはかなり難しいです…。
最悪の場合 Vim 本体の方を触る必要があるかもしれません。

**Comment by machakann** [comment]
ありがとうございます。テストは走っているようですし、大丈夫です。
困ったとしても別の端末などで試すことにします。
issue は閉じたほうがよいでしょうか？

**Comment by thinca** [comment]
どちらでも大丈夫です！

**Comment by machakann** [comment]
閉じます！ありがとうございました。
