### ISSUE TITLE
$THEMIS_VIM のデフォルト値を $VIM にしてほしい

### ISSUE THREAD

**Issue by Shougo** [thinca/vim-themis#20]
themis コマンドを実行した時に起動される Vim のパスですが、`$THEMIS_VIM` を使用することになっており、
これの初期値が vim になっています。

Vim から themis コマンドを起動する場合もあることを考えると、この環境変数の初期値は `$VIM` にしたほうが良いのではないかと思っています。 `$VIM` が空の時、"vim" とすることで互換性を保つことができます。

いかがでしょうか。

**Comment by thinca** [comment]
`$VIM` はディレクトリです。`$THEMIS_VIM` には実行に使う `vim` コマンドを指定します。

**Comment by Shougo** [comment]
たしかにそのとおりですね。`v:progname` を使えばできそうですが、そのくらいなら.vimrcでセットしたほうが良さそうです。クローズします。
