### ISSUE TITLE
Doesn't work on Cygwin on AppVeyor

### ISSUE THREAD

**Issue by k-takata** [thinca/vim-themis#23]
https://github.com/Shougo/vimproc.vim/pull/221#issuecomment-145229118
themisの問題と言うよりは、AppVeyorあるいはCygwinやVimの問題かもしれませんが、AppVeyor上のCygwin上でthemisが動きません。
動くようになるとありがたいです。

**Comment by thinca** [comment]
うまく動かなかった時のビルドのログって見れますでしょうか?

**Comment by thinca** [comment]
よく見たら該当コメントにリンクありました…。

**Comment by k-takata** [comment]
どうもAppVeyor上でCygwinのVimが動作しないようです。
appveyor.ymlから直接Vimを呼んでみたり、cmd /cを介したり、bashを介したり、mintty上で動かしてみたりと、いろいろ試したのですがダメでした。

**Comment by thinca** [comment]
おのれ AppVeyor...!

**Comment by thinca** [comment]
ちゃんと調査しようと思ったら手元の環境に Cygwin 欲しいけど、入れたくない…。

**Comment by k-takata** [comment]
AppVeyorが標準出力等をキャプチャーする仕組みが悪さをしているのではないかと推測していますが、全く見当がつきません。どうやってキャプチャーしているのかが分かれば、ローカルで再現したり、対策も考えられそうなのですが。

ローカルのCygwinではthemisもちゃんと動いていますし、themisの問題ではなさそうなので閉じます。
AppVeyor上でCygwin Vimを動かす方法が分かりましたら教えてください。

**Comment by thinca** [comment]
了解です！
