### ISSUE TITLE
意図せずスワップファイルが生成される場合がある

### ISSUE THREAD

**Issue by machakann** [thinca/vim-themis#30]
`.themisrc` に `noswapfile` を指定していても `themis test/test.vim` のように特定のテストファイルを指定して実行した場合にスワップファイルが生成される場合があります。これを避ける方法はないでしょうか？

**Comment by thinca** [comment]
修正しました。 e1aeee10fb52f95a08a7c967436e0ae5bee038f1
今は master にのみ入っていますが、もう少ししたら 1.5.1 としてタグを付けようと思うのでバージョンを固定して使いたい場合は hash を使うか、もうしばらくお待ちください。

**Comment by machakann** [comment]
生成されなくなりました、ありがとうございます。
