### ISSUE TITLE
AppVeyor で使うバイナリを github 上のものに切り替える

### ISSUE THREAD

**Issue by koron** [thinca/vim-themis#31]
今は files.kaoriya.net のものを使っていただいていますが
https://github.com/koron/vim-kaoriya/releases/latest
のものに切り替えることは可能でしょうか?
特に事故などが無い限り、正式リリースのたびに同じものをアップロードしてます。

理由はいくつかありますが
files.kaoriya.net は自前サーバのためサービスの継続性にお約束ができないことと、
また github のほうが AppVeyor とのネットワーク的な距離が近いことが期待できるのではないかなと。

古い 7.3 については別途考える必要があるとは考えています。
「ココに置くと良いのでは」みたいな提案がありましたら、お願いします。

**Comment by tyru** [comment]
そういえば kaoriya.net のサーバ負荷とか考えてませんでした。
今は nightly build もあるので本家をダウンロードしてきても良いような気がします。
@koron さんが +kaoriya 版を使ってもらった方が都合が良いと思うなら +kaoriya で良いと思います。

**Comment by thinca** [comment]
了解です。とりあえず最新版は files.kaoriy.net から落とすのをやめます。今までありがとうございました。
本家の nightly があるのならそちらを使うのも良さそうですが、どこから落とせるでしょうか? @tyru ちょっと把握していないので、教えて頂けると助かります！
古いバージョンはどうしますかね…どこでもいいといえばどこでもいいわけですが、どこがふさわしいのかは難しいですね。

**Comment by tyru** [comment]
@thinca ここです。
https://github.com/vim/vim-win32-installer/releases

**Comment by thinca** [comment]
なるほど。常に最新版を指しているポイントはなさそうですね(kaoriya on github もそうだけど)。
バージョンを固定する必要がありそうですかね。

**Comment by tyru** [comment]
とりあえず自分と vital.vim のリポジトリには issues 建てました。
他にも各個人のVimプラグインのリポジトリで参照してるかと思います (追いきれてない)。

**Comment by tyru** [comment]
> バージョンを固定する必要がありそうですかね。

vim-jp.org で kaoriya への最新版のリンク貼ってたような気がするので、(自動化されてる前提で、負担の掛からない範囲で) 同じように nightly build の最新版を指すURLがあると便利かも…とふと思ったんですが、静的ページだけでリダイレクトはできないですね…

**Comment by tyru** [comment]
あーでも URL だけ書いた .txt ファイルを置いとけば参照はできますね

**Comment by thinca** [comment]
誰がどこに置くんでしょうか?

**Comment by tyru** [comment]
自動化か手動かは分からないですが、
vim-jp のサイトのどこかに Vim の最新 nightly build の  URL 1行だけ書いた .txt ファイルを置いておいて、appveyor.yml のスクリプトから URL を取得してその URL からダウンロード、みたいな感じです。

**Comment by tyru** [comment]
URL は64bit版と32bit版等、複数あってもいいような気もします。
イメージとしてはよくOSのisoファイルなんかをホストするサイト置いてある、ハッシュ値だけ書いたテキストファイルです。

**Comment by thinca** [comment]
なるほど。一手間かかってしまうのでスクリプトが無駄に複雑になりそうですが、仕方ないかな…。

**Comment by koron** [comment]
えっと、状況としては、常に最新のバイナリのURLが取得 or 転送してくれる固定のURLが欲しいってことでOKですかね?

**Comment by thinca** [comment]
そうですね。それがあると常に最新が使えるので助かります。

**Comment by koron** [comment]
了解です。それは僕の方で引き受けます。
できたらココでアナウンスしますね。

**Comment by thinca** [comment]
おーありがとうございます！

**Comment by koron** [comment]
とりあえず jekyll だけでできないか jekyll-redirect-from + `redirect_to` で実験してみたけど
http://sandbox.vim-jp.org/goto/vim-win_x32/
HTMLの `<meta http-equiv="refresh">` なので、ダメそう。

次は外部サービス、検討します。

**Comment by koron** [comment]
PowerShell 使えばHTMLの parse も比較的簡単ですね…

```powershell
> $s = Invoke-WebRequest -URI "http://sandbox.vim-jp.org/goto/vim-win_x32/”
> $s.Links[0].href
https://github.com/vim/vim-win32-installer/releases/download/v7.4.1615/gvim_7.4.1615_x86.zip

> (New-Object Net.WebClient).DownloadFile($s.Links[0].href, "vim.zip")
```

@thinca こんな感じで良ければ、必要なものを用意してから PR 作りますけどいかがでしょう?

**Comment by thinca** [comment]
なるほど。その手法だと、@tyru さんが言っていたテキストファイルを置く手法と大差ない感じですかね?

**Comment by koron** [comment]
そうですね。

同じURLをダウンロードのためにブラウザからも使えるのと、
ZIP取得のための方法が確立している点がアドバンテージになります。

**Comment by thinca** [comment]
両立は良いですね。
懸念があるとすれば、appveyor の設定ファイルは設定例としてもリポジトリに含まれていて、各位がコピーして使うことを想定しているので、複雑になりすぎるとコピーした各位がメンテ不能にならないかという問題はありますが、現時点ですでにある程度複雑になってしまっているので、大差ないような気もしています。
他の人の意見も聞きたいという意味も込めて、上記の問題について @koron さんが問題無いだろうと判断したのであれば、その方向で進めてもらって大丈夫です :+1: 
やっぱまずいかもって感じられたならもうちょっと考えましょう。

**Comment by koron** [comment]
了解です。では進めます。 :+1:

**Comment by koron** [comment]
@thinca 7.3について1点、質問です。

利用している 7.3 が 20110306 と、やや古めなのにはなにか理由がありますか?
特になければ7.3系の最終バージョンである 20130706 (7.3.1314) へ
切り替えてしまおうと考えていますがどうでしょうか?

**Comment by koron** [comment]
中間報告: とりあえず redirects まで完了
http://vim-jp.org/redirects/

**Comment by koron** [comment]
#32 でいったんテスト中。

7.3 については files.kaoriya.net を参照していますが、それはまたあとで。

**Comment by koron** [comment]
#32 がマージされれば、本件は閉じて大丈夫です。

理想的な形にするまでには幾つか課題がありますが、
それらは https://github.com/vim-jp/redirects/issues で対処します。
時間があるときにでも目を通してください。

**Comment by koron** [comment]
7.3.1316 については koron/vim-kaoriya に pre-release として置いとくことにしました。
https://github.com/koron/vim-kaoriya/releases/tag/v7.3-legacy

**Comment by thinca** [comment]
> 利用している 7.3 が 20110306 と、やや古めなのにはなにか理由がありますか?

最初に作り始めた際に、とりあえず漠然と 7.3.0 までをサポートしようと考えて、手に入る一番古い 7.3 がそいつだった感じです。
サポート対象は適当なタイミングで見直した方がいいかもしれないとは考えていますが、Travis の Vim は今でも 7.3.429 っぽいので、7.3.0 とまではいかなくてもとりあえずここまではサポートしたいと考えてます。

**Comment by koron** [comment]
ああ、一番古い方だったんですね。追加しますので、少々お待ちを。

**Comment by koron** [comment]
僕の手元には 20110227 (7.3.135) が見つかったので、こっちに差し替えてみますかね…

**Comment by koron** [comment]
https://github.com/koron/vim-kaoriya/releases/tag/v7.3-legacy へ 20110227 (7.3.135) を追加しました。
これから redirects と appveyor.yml 更新します。

**Comment by koron** [comment]
完了。ということで 7.3.135 でテストを通ることを確認しました。
https://ci.appveyor.com/project/thinca/vim-themis/build/119/job/8ymiondwxnj3rifl

なお同ファイルは files.kaoriya.net にも置き直しましたが、まぁこれはどうでもよいですねw

**Comment by thinca** [comment]
ありがとうございます！！！

**Comment by koron** [comment]
(｀･ω･´)ゞ こちらこそありがとうございます。

[vim-jp/redirects](https://github.com/vim-jp/redirects) という副産物が、
うまく機能しそう & 他の使いみちもありそうで、
思ったより収穫が大きいかもしれません。

**Comment by thinca** [comment]
#32 をマージしたので閉じます。ありがとうございました！
