### ISSUE TITLE
themis#util#funcname(funcref) raise E724

### ISSUE THREAD

**Issue by lambdalisue** [thinca/vim-themis#33]
Like: https://travis-ci.org/vim-jp/vital.vim/jobs/117924274#L1500

Some workaround is required while recent Vim introduce a partial function and [the behaviour of `string({funcref})` has changed](https://github.com/vim/vim/commit/5c29154b521e9948190be653cfda666ecbb63b5b).

I know that @thinca is working on this but in case for vim-themis users.

**Comment by thinca** [comment]
Already fixed :) 80f1ee439ab9651d18fe8cabb7f7adb9f2a4eb09
