### ISSUE TITLE
Backward incompatible changes were introduced from v1.5.2

### ISSUE THREAD

**Issue by lambdalisue** [thinca/vim-themis#36]
### 状態
v1.5.1 で通るテストが v1.5.2 で落ちるようになった (vim: 7.4.1685)

### 原因
`Vital.Vim.ScriptLocal` にてスクリプトローカル変数を書き換えてテストを行っているが v1.5.2 だと書き換えが適用されていない感じ（下記が一番シンプルな関連箇所です）

- https://travis-ci.org/lambdalisue/vim-gita/jobs/122001827#L1564
- https://github.com/lambdalisue/vim-gita/blob/master/test/gita/core.vimspec#L64-L75
- https://github.com/lambdalisue/vim-gita/blob/master/autoload/gita/core.vim#L8-L19

上記の `let sv.references['foo'] = { 'worktree': 'foo' }` が適用されず、直後で `call themis#log(gita#core#_get_references())` しても空辞書が表示されます（ `gita/core.vim` に `gita#core#_get_references()` という `s:references` を返す関数を追加した場合）。

必要な情報などあれば追記します ;-)

**Comment by lambdalisue** [comment]
ちなみに上記の gita のテストはv1.5.1だとオールグリーンです。

**Comment by thinca** [comment]
テスト間の依存を極力なくすために、`Before all` などの各ブロックの中の変数はスコープ毎にコピーされるようになりました。
例えば上記の例だと、今までだと `sv` の変化が各テスト間で共有されてしまうので、テスト1を通った後でないと通らないテスト2というものが発生してしまう可能性があるためです。
今回の問題を避けるためには、コピーだと困るものを `Before all` から `Before` に移せば解決するはずです(`Before` と `After` はテスト毎に専用のスコープが作られて、その間はコピーは発生しない)。
この辺りやはりドキュメントに記載があった方が良さそうですね…説明がかなり難しくて投げてしまったところです。申し訳ない。
もしまだ何か問題があったら教えてください。

**Comment by lambdalisue** [comment]
なるほど・・・ただ [`sv` の割り当て部分](https://github.com/lambdalisue/vim-gita/blob/d52eb678d0b1695f776a0d6a1d78a7ebf2cab02f/test/gita/core.vimspec#L9-L10) を Before 内部に持って行き、以下のようにしても同じエラーが発生します。 
この書き方ならば `sv` のコピーは発生しないはずですよね？

```vim
  Before all
    let V = vital#of('vital')
    let Path = V.import('System.Filepath')
    let Guard = V.import('Vim.Guard')
    let ScriptLocal = V.import('Vim.ScriptLocal')
    let scriptfile = Path.realpath('autoload/gita/core.vim')

    " Create a mock Git working tree
    let root = tempname()
    let worktree = Path.join(root, 'i n s i d e')
    let repository = Path.join(worktree, '.git')
    let inside = Path.join(worktree, 'f o o', 'b a r')
    let outside = Path.join(root, 'o u t s i d e', 'f o o', 'b a r')
    lockvar root
    lockvar worktree
    lockvar repository
    lockvar inside
    lockvar outside
    call mkdir(repository, 'p')
    call mkdir(inside, 'p')
    call mkdir(outside, 'p')
  End

  After all
    " remote a temp directory
    let File = V.import('System.File')
    call File.rmdir(root, 'r')
  End

  Before
    let sf = ScriptLocal.sfuncs(scriptfile)
    let sv = ScriptLocal.svars(scriptfile)
    let guard = Guard.store(
          \ ['references', sv],
          \)
    let saved_getcwd = getcwd()
    execute printf('cd %s', fnameescape(root))
  End
```

必要であれば最小構成を作りますのでお申し付けください。

**Comment by thinca** [comment]
あれれ、それなら動く想定でした…。
すいませんが最小構成作って頂けると :bow: :sweat_drops:

**Comment by lambdalisue** [comment]
OK!

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/vim-themis-test

上記の構成で https://github.com/lambdalisue/vim-themis-test/blob/master/test/test.vimspec#L17 が通りません。コピーではないのであれば `Same` が通るはずですよね？

**Comment by thinca** [comment]
v1.5.2.1 ブランチで対策してみました。問題なければ、これを v1.5.2.1 として master にマージします。

**Comment by lambdalisue** [comment]
- `Before all` で `Vital.Vim.ScriptLocal` を使わない
- `Before all/After all` で `Vital.Vim.Guard` を使わない

を行ったところテストが通りましたので v1.5.2.1 で LGTM です！ありがとうございました！
