### ISSUE TITLE
Themis reports wrong result in Windows

### ISSUE THREAD

**Issue by lambdalisue** [thinca/vim-themis#47]
I'm sorry but it seems [the line](https://github.com/lambdalisue/vim-themis/blob/c33cd9958fe19f4f22b6d1b5c7a4ceb6a2fa5f69/bin/themis.bat#L25) should be REMOVE

The test failed but themis reported it successed. https://ci.appveyor.com/project/lambdalisue/gina-vim/build/408/job/0qjhorgvu99tdamt

Because I'm now moving, I temporary lost my Windows environment so I cannot confirm. I'm really sorry for this but could you confirm if the line I pointed was the reason and fix?

**Comment by thinca** [comment]
Thank you for reporting.  I fixed this.
