### ISSUE TITLE
Does any command convert vimspec to normal vim script

### ISSUE THREAD

**Issue by lymslive** [thinca/vim-themis#52]
In the help doc says, "*.vimspec" files will be converted to vim script, but how to save the converted "*.vim" file?

**Comment by thinca** [comment]
There is no way to do it.
Why you need it?

**Comment by thinca** [comment]
If you want to convert a vimspec file just a once, you can call an internal function.

`s:compile_specfile(specfile_path, result_path)` in `autocmd/themis/style/vimspec.vim` is it.  Add a global function to this file manually as below, and source the file and call it.

```vim
function CompileSpecfile(specfile_path, result_path)
  call s:compile_specfile(a:specfile_path, a:result_path)
endfunction
```

```vim
" call like this
call CompileSpecfile('/full_path/to/input.vimspec', '/full_path/to/output.vim')
```

There is no plan to add this as a feature.  Sorry.

> what the advantage of vimspec to viml?

Vimspec can make nested tests more easily.
Vimspec can describe tests by space separated sentence.

**Comment by lymslive** [comment]
well, thanks.
