### ISSUE TITLE
How to test input() and similar prompt functions?

### ISSUE THREAD

**Issue by kristijanhusak** [thinca/vim-themis#66]
Hi,

is there a way to test code that uses `input()` or similar prompt functions?

For example, how to test this?

```vimL
let g:added_name = ''
function! AddName() abort
  let g:added_name = input('Enter name', '')
endfunction
```

when i try to call the function from test, it just stucks:
```vimL
let s:suite = themis#suite('Test add name')

function! s:suite.test_add_name() abort
  call AddName()
endfunction
```

Only way i found is to wrap it in a function, and then mock it in the test. Is there maybe a better way?

**Comment by apieum** [comment]
I would use dependency injection with something like that (not tested)
```vim
let g:added_name = AddName(input)
function! AddName(input) abort
  return call(Function(a:input), ['Enter name', ''])
endfunction
```
Then call AddName in your test with the mock as argument

**Comment by kristijanhusak** [comment]
Thanks @apieum. I did something similar, just wanted to know if there's a better way.
