### ISSUE TITLE
Add ftdetect, ftplugin to vim runtime

### ISSUE THREAD

**Issue by Freed-Wu** [thinca/vim-themis#77]
Can we add `ftdetect/themis.vim`, `ftplugin/vimspec.vim`, ... to vim runtime? Refer https://github.com/vim/vim/pull/14380 It is not hard.

TIA!

**Comment by Shougo** [comment]
Why it is needed?

**Comment by Freed-Wu** [comment]
For those user who don't install themis, they can view it with syntax highlight. If they want to advanced function (execute it), they can install this plugin.

**Comment by thinca** [comment]
Vimspec syntax highlighting is not necessary for users who are not using themis.vim.
